language: java

jdk:
  - oraclejdk8
<<<<<<< HEAD

sudo: required
=======
  
  sudo: required
>>>>>>> 2e8448b90d6fb10174ba68f1e93bc4227c485b7b

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d
  - docker ps -a

before_script:
  - cd ../../src

script:
  - mvn test -Ptest-consumer,test-business
  - cd ../docker/dev
  - docker-compose stop
  - docker-compose rm -f
  - docker-compose up -d
  - docker ps -a
<<<<<<< HEAD
  - cd ../../src
=======
  - cd ../../src
>>>>>>> 2e8448b90d6fb10174ba68f1e93bc4227c485b7b
